# Generated by Django 6.0.6 on 2026-07-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Number of items in stock'),
        ),
    ]
