# Generated by Django 6.0.6 on 2026-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0002_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Product benefits (comma separated)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Filters', 'Filters'), ('Sensors', 'Sensors'), ('Purifiers', 'Purifiers'), ('Testing Kits', 'Testing Kits'), ('Softening Systems', 'Softening Systems'), ('Meters', 'Meters'), ('Pitchers', 'Pitchers'), ('Monitors', 'Monitors')], default='Filters', help_text='Product category', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Discount percentage', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is product active?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Is product on sale?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Product price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Average rating', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, help_text='Number of reviews', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_offer',
            field=models.CharField(blank=True, help_text='Special offer text (e.g., Buy 2 Get 1 Free)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last updated date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_created_e1ba5f_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
