# Generated by Django 6.0.6 on 2026-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0003_alter_product_options_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_name_6f9890_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_fce6e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_cb485f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_e1ba5f_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Filters', 'Filters'), ('Sensors', 'Sensors'), ('Purifiers', 'Purifiers'), ('Testing Kits', 'Testing Kits'), ('Softening Systems', 'Softening Systems'), ('Meters', 'Meters'), ('Pitchers', 'Pitchers'), ('Monitors', 'Monitors')], default='Filters', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_offer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
