# Generated by Django 6.0.6 on 2026-07-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0005_alter_inventory_product'),
    ]

    operations = [
    ]
