# Generated by Django 6.0.6 on 2026-07-08 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0005_inventory_inventoryalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('has_diabetes', models.CharField(choices=[('yes', 'Yes, I have Diabetes'), ('no', "No, I don't have Diabetes"), ('pre', 'Pre-diabetic'), ('gestational', 'Gestational Diabetes'), ('unsure', 'Not sure')], default='no', max_length=20, verbose_name='Diabetes Status')),
                ('diabetes_notes', models.TextField(blank=True, help_text='Additional notes about diabetes condition (e.g., Type 1, Type 2, medications)', null=True, verbose_name='Diabetes Notes')),
                ('blood_pressure', models.CharField(choices=[('normal', 'Normal (Less than 120/80)'), ('elevated', 'Elevated (120-129/80)'), ('stage1', 'Stage 1 Hypertension (130-139/80-89)'), ('stage2', 'Stage 2 Hypertension (140+/90+)'), ('crisis', 'Hypertensive Crisis (180+/120+)'), ('unsure', "Not sure / Don't know")], default='unsure', max_length=20, verbose_name='Blood Pressure Status')),
                ('blood_pressure_notes', models.TextField(blank=True, help_text='Additional notes about blood pressure (e.g., medications, readings)', null=True, verbose_name='Blood Pressure Notes')),
                ('other_health_conditions', models.TextField(blank=True, help_text='Any other health conditions or allergies', null=True, verbose_name='Other Health Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
