# Generated by Django 6.0.6 on 2026-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0006_force_set_null_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description shown in product cards and dropdown menus (max 300 chars)', max_length=300, null=True),
        ),
    ]
