# Generated by Django 6.0.6 on 2026-07-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0006_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='blood_pressure_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='diabetes_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_diabetes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='other_health_conditions',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_pressure_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='diabetes_type',
            field=models.CharField(choices=[('none', 'None'), ('type1', 'Type 1 Diabetes'), ('type2', 'Type 2 Diabetes'), ('gestational', 'Gestational Diabetes')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_high_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_stock',
            field=models.IntegerField(default=0, help_text='Stock after this movement'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='previous_stock',
            field=models.IntegerField(default=0, help_text='Stock before this movement'),
        ),
        migrations.DeleteModel(
            name='InventoryAlert',
        ),
    ]
